#!/usr/bin/env python3
import argparse
import json
import os
import re
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, replace
from typing import Any, Dict, Optional

import boto3
from botocore.exceptions import ClientError
from gha_agent_review_agent.providers import env_value, invoke_provider, resolve_provider


TAG_KEY = "purpose"
TAG_VALUE = "gha-agent-review"
MANAGED_BY_KEY = "managed-by"
MANAGED_BY_VALUE = "github-actions"
AZURE_MANAGEMENT_API_VERSION = "2024-10-01"


class HttpStatusError(RuntimeError):
    def __init__(self, status_code: int, url: str, body: str) -> None:
        super().__init__(f"Provider setup request failed: {status_code} {url}: {body}")
        self.status_code = status_code
        self.url = url
        self.body = body


@dataclass(frozen=True)
class AzureSetupOptions:
    access_token: str = ""
    subscription_id: str = ""
    resource_group: str = ""
    account_name: str = ""
    location: str = ""
    account_sku: str = "S0"
    deployment_model_name: str = ""
    deployment_model_version: str = ""
    deployment_sku_name: str = "Standard"
    deployment_capacity: int = 1
    management_api_version: str = AZURE_MANAGEMENT_API_VERSION

    @property
    def configured(self) -> bool:
        return bool(self.access_token and self.subscription_id and self.resource_group and self.account_name)


def setup_tags() -> Dict[str, str]:
    return {
        TAG_KEY: TAG_VALUE,
        MANAGED_BY_KEY: MANAGED_BY_VALUE,
    }


def request_json(
    method: str,
    url: str,
    headers: Dict[str, str],
    payload: Optional[Dict[str, Any]] = None,
    allowed_statuses: tuple[int, ...] = (200,),
) -> Dict[str, Any]:
    body = None if payload is None else json.dumps(payload).encode("utf-8")
    request_headers = {"Content-Type": "application/json", **headers}
    request = urllib.request.Request(url, data=body, method=method, headers=request_headers)
    try:
        with urllib.request.urlopen(request, timeout=120) as response:
            response_body = response.read().decode("utf-8")
            if response.status not in allowed_statuses:
                raise HttpStatusError(response.status, url, response_body)
            return json.loads(response_body) if response_body else {}
    except urllib.error.HTTPError as exc:
        details = exc.read().decode("utf-8", errors="replace")
        raise HttpStatusError(exc.code, url, details) from exc


def merge_tags(existing_tags: Optional[Dict[str, Any]]) -> Dict[str, str]:
    merged = {str(key): str(value) for key, value in (existing_tags or {}).items()}
    merged.update(setup_tags())
    return merged


def aggregate_status(*statuses: str) -> str:
    values = {status for status in statuses if status and status != "skipped"}
    if "created" in values:
        return "created"
    if "updated" in values:
        return "updated"
    if "found" in values:
        return "found"
    return "preflighted"


def list_prompt_marker(client: Any, prompt_name: str) -> Optional[Dict[str, Any]]:
    paginator = client.get_paginator("list_prompts")
    for page in paginator.paginate():
        for prompt in page.get("promptSummaries", []):
            arn = prompt.get("arn")
            if not arn:
                continue
            tags = client.list_tags_for_resource(resourceArn=arn).get("tags", {})
            if tags.get(TAG_KEY) == TAG_VALUE and prompt.get("name") == prompt_name:
                return prompt
    return None


def create_prompt_marker(client: Any, prompt_name: str, model_id: str) -> Dict[str, Any]:
    response = client.create_prompt(
        name=prompt_name,
        description="Marker prompt for the GHA AI Agent Review GitHub Action.",
        tags=setup_tags(),
        defaultVariant="gha-agent-review-marker",
        variants=[
            {
                "name": "gha-agent-review-marker",
                "modelId": model_id,
                "templateType": "TEXT",
                "templateConfiguration": {
                    "text": {
                        "text": "GHA AI Agent Review marker prompt. Runtime prompts are generated by the GitHub Action."
                    }
                },
                "inferenceConfiguration": {
                    "text": {
                        "maxTokens": 32,
                        "temperature": 0,
                        "topP": 1,
                    }
                },
            }
        ],
    )
    return response


def preflight_model(region: str, model_id: str) -> None:
    runtime = boto3.client("bedrock-runtime", region_name=region)
    runtime.converse(
        modelId=model_id,
        messages=[
            {
                "role": "user",
                "content": [{"text": "Return only: ok"}],
            }
        ],
        inferenceConfig={"maxTokens": 8, "temperature": 0},
    )


def write_output(path: str, output: Dict[str, Any]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as output_file:
        json.dump(output, output_file, indent=2, sort_keys=True, default=str)


def preflight_direct_provider(config: Any) -> None:
    invoke_provider(config, "Return only: ok", max_tokens=16)


def safe_resource(value: str) -> str:
    return urllib.parse.quote(value, safe="")


def azure_management_url(options: AzureSetupOptions, suffix: str = "") -> str:
    subscription = safe_resource(options.subscription_id)
    resource_group = safe_resource(options.resource_group)
    account_name = safe_resource(options.account_name)
    suffix = suffix if suffix.startswith("/") or not suffix else f"/{suffix}"
    api_version = urllib.parse.quote(options.management_api_version, safe="")
    return (
        "https://management.azure.com/"
        f"subscriptions/{subscription}/resourceGroups/{resource_group}/providers/"
        f"Microsoft.CognitiveServices/accounts/{account_name}{suffix}?api-version={api_version}"
    )


def azure_headers(options: AzureSetupOptions) -> Dict[str, str]:
    return {"Authorization": f"Bearer {options.access_token}"}


def ensure_azure_account(options: AzureSetupOptions) -> Dict[str, Any]:
    url = azure_management_url(options)
    headers = azure_headers(options)
    try:
        account = request_json("GET", url, headers)
    except HttpStatusError as exc:
        if exc.status_code != 404:
            raise
        if not options.location:
            raise ValueError("azure-openai-location is required to create a missing Azure OpenAI account.") from exc
        payload = {
            "location": options.location,
            "kind": "OpenAI",
            "sku": {"name": options.account_sku or "S0"},
            "properties": {
                "customSubDomainName": options.account_name,
            },
            "tags": setup_tags(),
        }
        account = request_json("PUT", url, headers, payload, allowed_statuses=(200, 201, 202))
        if not account:
            account = {"name": options.account_name, "tags": payload["tags"]}
        return {"status": "created", "resource": account}

    existing_tags = {str(key): str(value) for key, value in (account.get("tags") or {}).items()}
    merged_tags = merge_tags(existing_tags)
    if existing_tags != merged_tags:
        account = request_json("PATCH", url, headers, {"tags": merged_tags}, allowed_statuses=(200, 202))
        if not account:
            account = {"name": options.account_name, "tags": merged_tags}
        return {"status": "updated", "resource": account}
    return {"status": "found", "resource": account}


def ensure_azure_deployment(options: AzureSetupOptions, deployment_name: str) -> Dict[str, Any]:
    if not deployment_name:
        return {"status": "skipped", "reason": "model-id is required to check Azure OpenAI deployment setup."}

    suffix = f"/deployments/{safe_resource(deployment_name)}"
    url = azure_management_url(options, suffix)
    headers = azure_headers(options)
    try:
        deployment = request_json("GET", url, headers)
    except HttpStatusError as exc:
        if exc.status_code != 404:
            raise
        if not options.deployment_model_name:
            return {
                "status": "skipped",
                "reason": "azure-openai-deployment-model-name is required to create a missing deployment.",
            }
        model = {
            "format": "OpenAI",
            "name": options.deployment_model_name,
        }
        if options.deployment_model_version:
            model["version"] = options.deployment_model_version
        payload = {
            "sku": {
                "name": options.deployment_sku_name or "Standard",
                "capacity": options.deployment_capacity or 1,
            },
            "properties": {"model": model},
            "tags": setup_tags(),
        }
        deployment = request_json("PUT", url, headers, payload, allowed_statuses=(200, 201, 202))
        if not deployment:
            deployment = {"name": deployment_name, "tags": payload["tags"]}
        return {"status": "created", "resource": deployment}

    existing_tags = {str(key): str(value) for key, value in (deployment.get("tags") or {}).items()}
    merged_tags = merge_tags(existing_tags)
    if existing_tags != merged_tags:
        payload = {
            "properties": deployment.get("properties") or {},
            "sku": deployment.get("sku") or {
                "name": options.deployment_sku_name or "Standard",
                "capacity": options.deployment_capacity or 1,
            },
            "tags": merged_tags,
        }
        deployment = request_json("PUT", url, headers, payload, allowed_statuses=(200, 201, 202))
        if not deployment:
            deployment = {"name": deployment_name, "tags": merged_tags}
        return {"status": "updated", "resource": deployment}
    return {"status": "found", "resource": deployment}


def azure_account_key(options: AzureSetupOptions) -> str:
    response = request_json(
        "POST",
        azure_management_url(options, "/listKeys"),
        azure_headers(options),
        allowed_statuses=(200,),
    )
    return str(response.get("key1") or response.get("key2") or "")


def azure_endpoint_from_account(config: Any, options: AzureSetupOptions, account: Dict[str, Any]) -> str:
    configured_endpoint = str(getattr(config, "azure_openai_endpoint", "") or "").strip()
    if configured_endpoint:
        return configured_endpoint
    properties = account.get("properties") or {}
    discovered_endpoint = str(properties.get("endpoint") or "").strip()
    if discovered_endpoint:
        return discovered_endpoint
    return f"https://{options.account_name}.openai.azure.com"


def ensure_azure_setup(config: Any, options: AzureSetupOptions, marker_name: str) -> Dict[str, Any]:
    if not options.configured:
        return {
            "status": "preflighted",
            "provider": "azure-openai",
            "reason": "Azure management setup skipped because azure-access-token, subscription, resource group, or account name was not configured.",
            "tag": setup_tags(),
            "runtime_env": {
                "AZURE_OPENAI_API_KEY": str(getattr(config, "azure_openai_api_key", "") or ""),
                "AZURE_OPENAI_ENDPOINT": str(getattr(config, "azure_openai_endpoint", "") or ""),
                "AZURE_OPENAI_API_VERSION": str(getattr(config, "azure_openai_api_version", "") or ""),
            },
        }

    account_result = ensure_azure_account(options)
    deployment_result = ensure_azure_deployment(options, config.model_id)
    account_resource = account_result.get("resource") or {}
    runtime_env = {
        "AZURE_OPENAI_ENDPOINT": azure_endpoint_from_account(config, options, account_resource),
        "AZURE_OPENAI_API_VERSION": str(getattr(config, "azure_openai_api_version", "") or ""),
    }
    configured_key = str(getattr(config, "azure_openai_api_key", "") or "").strip()
    if configured_key:
        runtime_env["AZURE_OPENAI_API_KEY"] = configured_key
    else:
        key = azure_account_key(options)
        if key:
            runtime_env["AZURE_OPENAI_API_KEY"] = key
    return {
        "status": aggregate_status(account_result["status"], deployment_result["status"]),
        "provider": "azure-openai",
        "prompt_name": marker_name,
        "tag": setup_tags(),
        "runtime_env": runtime_env,
        "account": {
            "status": account_result["status"],
            **account_resource,
        },
        "deployment": {
            "status": deployment_result["status"],
            **(deployment_result.get("resource") or {}),
        },
    }


def google_marker_file_name(marker_name: str) -> str:
    marker_id = re.sub(r"[^a-z0-9-]+", "-", marker_name.lower()).strip("-") or "gha-agent-review"
    marker_id = marker_id[:40].strip("-") or "gha-agent-review"
    return f"files/{marker_id}"


def google_headers(config: Any) -> Dict[str, str]:
    return {"x-goog-api-key": config.google_api_key}


def find_google_marker(config: Any, marker_name: str) -> Optional[Dict[str, Any]]:
    expected_name = google_marker_file_name(marker_name)
    page_token = ""
    while True:
        query = {"pageSize": "100"}
        if page_token:
            query["pageToken"] = page_token
        url = "https://generativelanguage.googleapis.com/v1beta/files?" + urllib.parse.urlencode(query)
        response = request_json("GET", url, google_headers(config))
        for file_info in response.get("files") or []:
            if file_info.get("name") == expected_name or file_info.get("displayName") == marker_name:
                return file_info
        page_token = str(response.get("nextPageToken") or "")
        if not page_token:
            return None


def ensure_google_marker(config: Any, marker_name: str) -> Dict[str, Any]:
    marker = find_google_marker(config, marker_name)
    if marker:
        return {
            "status": "found",
            "provider": "google",
            "prompt_name": marker_name,
            "tag": setup_tags(),
            "marker": marker,
        }

    marker_name_value = google_marker_file_name(marker_name)
    marker = request_json(
        "POST",
        "https://generativelanguage.googleapis.com/v1beta/files",
        google_headers(config),
        {
            "file": {
                "name": marker_name_value,
                "displayName": marker_name,
            }
        },
        allowed_statuses=(200, 201),
    )
    marker_resource = marker.get("file") or marker
    return {
        "status": "created",
        "provider": "google",
        "prompt_name": marker_name,
        "tag": setup_tags(),
        "marker": marker_resource,
    }


def azure_setup_options_from_args(args: Any) -> AzureSetupOptions:
    return AzureSetupOptions(
        access_token=args.azure_access_token
        or env_value(os.environ, "AZURE_ACCESS_TOKEN", "GHA_AI_AGENT_AZURE_ACCESS_TOKEN"),
        subscription_id=args.azure_subscription_id
        or env_value(os.environ, "AZURE_SUBSCRIPTION_ID", "GHA_AI_AGENT_AZURE_SUBSCRIPTION_ID"),
        resource_group=args.azure_resource_group
        or env_value(os.environ, "AZURE_RESOURCE_GROUP", "GHA_AI_AGENT_AZURE_RESOURCE_GROUP"),
        account_name=args.azure_openai_account_name
        or env_value(os.environ, "AZURE_OPENAI_ACCOUNT_NAME", "GHA_AI_AGENT_AZURE_OPENAI_ACCOUNT_NAME"),
        location=args.azure_openai_location
        or env_value(os.environ, "AZURE_OPENAI_LOCATION", "GHA_AI_AGENT_AZURE_OPENAI_LOCATION"),
        account_sku=args.azure_openai_account_sku
        or env_value(os.environ, "AZURE_OPENAI_ACCOUNT_SKU", "GHA_AI_AGENT_AZURE_OPENAI_ACCOUNT_SKU")
        or "S0",
        deployment_model_name=args.azure_openai_deployment_model_name
        or env_value(
            os.environ,
            "AZURE_OPENAI_DEPLOYMENT_MODEL_NAME",
            "GHA_AI_AGENT_AZURE_OPENAI_DEPLOYMENT_MODEL_NAME",
        ),
        deployment_model_version=args.azure_openai_deployment_model_version
        or env_value(
            os.environ,
            "AZURE_OPENAI_DEPLOYMENT_MODEL_VERSION",
            "GHA_AI_AGENT_AZURE_OPENAI_DEPLOYMENT_MODEL_VERSION",
        ),
        deployment_sku_name=args.azure_openai_deployment_sku_name
        or env_value(
            os.environ,
            "AZURE_OPENAI_DEPLOYMENT_SKU_NAME",
            "GHA_AI_AGENT_AZURE_OPENAI_DEPLOYMENT_SKU_NAME",
        )
        or "Standard",
        deployment_capacity=args.azure_openai_deployment_capacity,
    )


def provider_env_from_args(args: Any) -> Dict[str, str]:
    env = dict(os.environ)
    cli_values = {
        "AZURE_ACCESS_TOKEN": args.azure_access_token,
        "AZURE_SUBSCRIPTION_ID": args.azure_subscription_id,
        "AZURE_RESOURCE_GROUP": args.azure_resource_group,
        "AZURE_OPENAI_ACCOUNT_NAME": args.azure_openai_account_name,
    }
    for key, value in cli_values.items():
        if value:
            env[key] = value
    return env


def write_env_output(path: str, values: Dict[str, str]) -> None:
    if not path or not values:
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as env_file:
        for key, value in values.items():
            if value:
                env_file.write(f"{key}={value}\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--aws-region", default="")
    parser.add_argument("--model-id", default="")
    parser.add_argument("--provider", default="auto")
    parser.add_argument("--azure-openai-endpoint", default="")
    parser.add_argument("--azure-openai-api-version", default="")
    parser.add_argument("--azure-access-token", default="")
    parser.add_argument("--azure-subscription-id", default="")
    parser.add_argument("--azure-resource-group", default="")
    parser.add_argument("--azure-openai-account-name", default="")
    parser.add_argument("--azure-openai-location", default="")
    parser.add_argument("--azure-openai-account-sku", default="S0")
    parser.add_argument("--azure-openai-deployment-model-name", default="")
    parser.add_argument("--azure-openai-deployment-model-version", default="")
    parser.add_argument("--azure-openai-deployment-sku-name", default="Standard")
    parser.add_argument("--azure-openai-deployment-capacity", type=int, default=1)
    parser.add_argument("--prompt-name", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--env-output", default="")
    args = parser.parse_args()

    config = resolve_provider(
        provider=args.provider,
        model_id=args.model_id,
        aws_region=args.aws_region,
        azure_openai_endpoint=args.azure_openai_endpoint,
        azure_openai_api_version=args.azure_openai_api_version,
        env=provider_env_from_args(args),
    )

    if config.provider == "azure-openai":
        setup = ensure_azure_setup(config, azure_setup_options_from_args(args), args.prompt_name)
        runtime_env = setup.get("runtime_env") or {}
        write_env_output(args.env_output, runtime_env)
        output_setup = {key: value for key, value in setup.items() if key != "runtime_env"}
        config = replace(
            config,
            azure_openai_api_key=runtime_env.get("AZURE_OPENAI_API_KEY") or config.azure_openai_api_key,
            azure_openai_endpoint=runtime_env.get("AZURE_OPENAI_ENDPOINT") or config.azure_openai_endpoint,
        )
        preflight_direct_provider(config)
        write_output(
            args.output,
            {
                **output_setup,
                "provider": config.provider,
                "prompt_name": args.prompt_name,
                "region": config.aws_region,
                "model_id": config.model_id,
            },
        )
        print(f"Azure OpenAI setup {setup['status']}; provider preflight completed: {config.model_id}")
        return 0

    if config.provider == "google":
        setup = ensure_google_marker(config, args.prompt_name)
        preflight_direct_provider(config)
        write_output(
            args.output,
            {
                **setup,
                "provider": config.provider,
                "prompt_name": args.prompt_name,
                "region": config.aws_region,
                "model_id": config.model_id,
            },
        )
        print(f"Google Gemini marker {setup['status']}; provider preflight completed: {config.model_id}")
        return 0

    if config.provider != "bedrock":
        preflight_direct_provider(config)
        write_output(
            args.output,
            {
                "status": "preflighted",
                "provider": config.provider,
                "prompt_name": args.prompt_name,
                "region": config.aws_region,
                "model_id": config.model_id,
            },
        )
        print(f"Provider preflight completed for {config.provider}: {config.model_id}")
        return 0

    sts = boto3.client("sts", region_name=config.aws_region)
    identity = sts.get_caller_identity()

    bedrock_agent = boto3.client("bedrock-agent", region_name=config.aws_region)
    marker = list_prompt_marker(bedrock_agent, args.prompt_name)
    status = "found"

    if not marker:
        marker = create_prompt_marker(bedrock_agent, args.prompt_name, config.model_id)
        status = "created"

    try:
        preflight_model(config.aws_region, config.model_id)
    except ClientError as exc:
        code = exc.response.get("Error", {}).get("Code", "Unknown")
        message = exc.response.get("Error", {}).get("Message", str(exc))
        raise RuntimeError(
            f"Bedrock model preflight failed for {config.model_id} in {config.aws_region}: {code}: {message}. "
            "Verify Anthropic model access is enabled for this AWS account and region."
        ) from exc

    output = {
        "status": status,
        "provider": config.provider,
        "prompt_name": args.prompt_name,
        "tag": setup_tags(),
        "aws_account": identity.get("Account"),
        "caller_arn": identity.get("Arn"),
        "region": config.aws_region,
        "model_id": config.model_id,
        "marker": marker,
    }

    write_output(args.output, output)
    print(f"Bedrock prompt marker {status}: {args.prompt_name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
